---
abstract: 'serve HTTP with C<IO::Async>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  HTTP::Response: 0
  IO::Async::Test: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-HTTP-Server
provides:
  Net::Async::HTTP::Server:
    file: lib/Net/Async/HTTP/Server.pm
    version: 0.02
  Net::Async::HTTP::Server::Protocol:
    file: lib/Net/Async/HTTP/Server/Protocol.pm
    version: 0.02
  Net::Async::HTTP::Server::Request:
    file: lib/Net/Async/HTTP/Server/Request.pm
    version: 0.02
requires:
  HTTP::Request: 0
  IO::Async: 0.54
  IO::Async::Listener: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
